name: "Build size check"

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch where to fetch bunlemonrc"
        required: false
        default: "master"
        type: string
      runner:
        description: "Specify runner. Defaults to checking visibility"
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  build-size-check:
    name: Bundlemon Build Size Check
    runs-on: ${{ inputs.runner }}

    steps:
      # Check out base (target) branch at the commit where the PR branched off
      - name: Check out base branch
        uses: actions/checkout@v4

      - name: Install apt libraries
        run: sudo apt install gettext -y

      # Check if .bundlemonrc exists in the caller repo
      - name: Check for .bundlemonrc in caller repo
        id: check_bundlemonrc
        run: |
          if [ -f ".bundlemonrc" ]; then
            echo "✅ Using .bundlemonrc from caller repo"
            echo "USE_CALLER_CONFIG=true" >> $GITHUB_ENV
          else
            echo "⚠️ No .bundlemonrc in caller repo, will try fetching from workflow repo"
            echo "USE_CALLER_CONFIG=false" >> $GITHUB_ENV
          fi

      # Fetch .bundlemonrc from the workflow repo branch if needed
      - name: Fetch .bundlemonrc from reusable workflow repo
        if: env.USE_CALLER_CONFIG == 'false'
        run: |
          echo "Downloading .bundlemonrc from EyeSeeTea/github-workflows (branch: ${{ inputs.branch_name }})"
          BUNDLEMON_URL="https://raw.githubusercontent.com/EyeSeeTea/github-workflows/${{ inputs.branch_name }}/.bundlemonrc"
          if curl --silent --fail --output .bundlemonrc "$BUNDLEMON_URL"; then
            echo "✅ Successfully downloaded .bundlemonrc"
          else
            echo "❌ Failed to fetch .bundlemonrc from the reusable workflow repo. Skipping build size check."
            exit 1
          fi

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'  # Use the Node.js version specified in .nvmrc
          cache: 'yarn'

      # Install and build
      - name: Install and build
        run: |
          yarn install --frozen-lockfile --silent
          yarn build

      - name: BundleMon
        uses: lironer/bundlemon-action@v1