name: "Master Workflow"

on:
  workflow_call:
    inputs:
      languages:
        description: "Languages to analyze"
        required: false
        default: '["javascript-typescript"]'
        type: string
      build_mode:
        description: "Build mode for CodeQL analysis"
        required: false
        default: "none"
        type: string
      bundlemonrc_branch_name:
        description: "Branch where to fetch bunlemonrc" # couldn't find a way to get the workflow branch from caller. Need to pass for testing
        required: false
        default: "master"
        type: string
      runner:
        description: "Specify runner. Defaults to checking visibility"
        required: false
        type: string
      workflows_to_run:
        description: 'Comma-separated list of workflows to run (e.g., flow1,flow2)'
        required: false
        default: 'all' #'run-tests,codeql-scan,build-check'
        type: string

jobs:
  run-tests:
    if: contains(inputs.workflows_to_run, 'run-tests') || contains(inputs.workflows_to_run, 'all')
    uses: ./.github/workflows/app-test.yml
    with:
      runner: ${{ inputs.runner || (github.event.repository.private && 'self-hosted') || 'ubuntu-latest' }}

  #skip if private repo
  codeql-scan:
    if: contains(inputs.workflows_to_run, 'codeql-scan') || contains(inputs.workflows_to_run, 'all')
    uses: ./.github/workflows/codeql.yml
    with:
      languages: ${{ inputs.languages }}
      build_mode: ${{ inputs.build_mode }}
      runner: ${{ inputs.runner || 'ubuntu-latest' }}

  build-check:
    if: contains(inputs.workflows_to_run, 'build-check') || contains(inputs.workflows_to_run, 'all')
    uses: ./.github/workflows/bundlemon-build-size.yml
    with:
      branch_name: ${{ inputs.bundlemonrc_branch_name }}
      runner: ${{ inputs.runner || (github.event.repository.private && 'self-hosted') || 'ubuntu-latest' }}